bool: True
load_models:
  - oct_1f-apr_2f.pkl
  - oct_1f-apr_1f.pkl
load_data:
  - rabi_v1.0.pkl
predictors: 
  - 'oct_1f'
  - 'oct_2f'
  - 'nov_1f'
  - 'nov_2f'
  - 'dec_1f'
  - 'dec_2f'
  - 'jan_1f'
  - 'jan_2f'
  - 'feb_1f'
  - 'feb_2f'
  - 'mar_1f'
  - 'mar_2f'
  - 'apr_1f'
  - 'apr_2f'
target: crop_type