wandb_version: 1

artifact_paths:
  desc: null
  value:
    cleaning:
      input_path: /Users/sreekrishna/Krishi_DSS/KDSS_ML/artifacts/data/raw/master_pickle.pkl
      output_path: /Users/sreekrishna/Krishi_DSS/KDSS_ML/artifacts/data/preprocessed/processed_data.pkl
    trained_models:
      path: /Users/sreekrishna/Krishi_DSS/KDSS_ML/artifacts/trained_models/classifier.pkl
featurize:
  desc: null
  value:
    train_test_split:
      seed: 42
      val_size: 0.2
      test_size: 0.2
      stratify:
      - crop_type
      - sowing_period
      - harvest_period
    label_encode:
      target: crop_type
      predictors:
      - oct_1f
      - oct_2f
      - nov_1f
      - nov_2f
      - dec_1f
      - dec_2f
      - jan_1f
      - jan_2f
      - feb_1f
      - feb_2f
      - mar_1f
      - mar_2f
      - apr_1f
      - apr_2f
    scaler_type: StandardScaler
train:
  desc: null
  value:
    target: crop_type
    model_type: XGBClassifier
    raw_metric: precision
    tuning_metric_type: harmonic_mean
    seed: 42
    n_estimators:
    - 5
    - 15
    - 5
    learning_rate:
    - 0.05
    - 0.55
    - 0.1
    max_depth:
    - 1
    - 5
    - 1
splits:
  desc: null
  value: {}
cleaning:
  desc: null
  value:
    output_path: /Users/sreekrishna/Krishi_DSS/KDSS_ML/data/rabi_v1.0
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.4
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710240208.0
    t:
      1:
      - 1
      - 5
      - 6
      - 50
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 6
      - 50
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.16.4
      8:
      - 4
      - 5
      13: darwin-arm64
