defaults:
 - data_cleaning: preprocess
 - featurization: featurize
 - inference: eval
 - train: modelling
 - _self_

data_cleaning:
  bool: False
  output_path: ${hydra:runtime.cwd}/data/preprocessed/rabi_v1.0.pkl

featurize:
  train_val_test_split:
    bool: False
  
# train:  
#   modelling_params:  
#     bool: False

