defaults:
 - artifact_paths: paths
 - featurize: 
      - featurize
      - splits
 - inference: eval
 - train: modelling
 - _self_

artifact_paths:  
  cleaning:
    output_path: ${hydra:runtime.cwd}/data/preprocessed/rabi_v1.0.pkl

featurize:
  train_test_split:
    bool: False

inference:
  load_models:
    - oct_1f-apr_2f.pkl
    - oct_1f-apr_1f.pkl
  

# train:  
#   modelling_params:  
#     bool: False

