training_params:  
  bool: True
  target: crop_type
  model_type: XGBClassifier
  raw_metric: precision
  tuning_metric_type: harmonic_mean
  seed: 42
  n_estimators: 
    - 5 # Start
    - 15 # End
    - 5 # Step
  learning_rate:
    - 0.05 # Start
    - 0.55 # End
    - 0.1 # Step
  max_depth: 
    - 1 # Start
    - 5 # End
    - 1 # Step
model_dir_path: ${hydra:runtime.cwd}/trained_models/